# Generated by Django 3.0.6 on 2020-10-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена в $')),
                ('image', models.ImageField(default='pictures', upload_to='services/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Услуга/товар',
                'verbose_name_plural': 'Услуги/товары',
            },
        ),
    ]
